### ISSUE TITLE
About the training dataset and code

### ISSUE THREAD

**Issue by ligaoqi2** [RizwanMunawar/yolov7-pose-estimation#10]
Amazing repo!
But I can't find the training dataset and code, only the inferenece code,
How long will be the dataset and training code are released?
Thanks~

**Comment by RizwanMunawar** [comment]
@ligaoqi2! I am planning to release it soon, but maybe it will release in the coming month or later.

**Comment by ligaoqi2** [comment]
OK, Thank you very much
