### ISSUE TITLE
[Modifications] Plotting x, y displacement and replacing bounding box with a circle ?

### ISSUE THREAD

**Issue by timtensor** [RizwanMunawar/yolov7-pose-estimation#11]
Hi, first of all great work done for combining pose estimation and object tracking. I am trying to modify the implementation to basically plot 
1. Heat map of few of the tracked objects to have some kind of the birds eye view . The idea was to plot if per frame and to have it visualized on top of the video stream (like realtime analysis) . Something like attached in the image itself . 
2. Is it possible to draw instead of a rectangular bounding box , some kind of a circular disc on the foot of the players for better and easier visualization?  

Could you please provide some guidelines on it ?
![image](https://user-images.githubusercontent.com/49288450/207072001-436df09c-a98a-4239-a45a-f106d4e32d88.png)

**Comment by timtensor** [comment]
Thanks for the info ,
1. I will check them out .  I think the idea is just to plot velocity as you have shown . Is there any explanation of it or where the modifications have been made. I could not find much information.

2- Can you tell me where to modify the code in order to have the cirular disc visualization ?

**Comment by RizwanMunawar** [comment]
@timtensor! You will need to do all your work in plot.py or some in detect.py. For circular disc plotting, you will need to write the custom functions. You can take reference from the mentioned link below.
https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-football-players.ipynb

**Comment by RizwanMunawar** [comment]
@timtensor I am closing this issue, as this is a question that has been answered last month. Feel free to open new issues, if you will face any problems with the code.
