### ISSUE TITLE
Loading output data to other usage

### ISSUE THREAD

**Issue by jossevessies** [RizwanMunawar/yolov7-pose-estimation#15]
Dear Rizwan,

Thank you for this supertight piece of code!
It was great to get it running in notime.

I want to load out the capturepoints of the skeleton and use them in touchdesigner for a small testproject.
So I'm deciphering the shape and steps of the output array.

Any chance you can provide some hints?

Thanks a lot!

**Comment by RizwanMunawar** [comment]
@jossevessies! My pleasure. The pose model will provide you with all pose values for specific objects. At the backend, the pose model that has been used is 2D. Its sample is shown below.
![204121854-ba14ce4c-d9fd-4244-92b7-038ef93199af](https://user-images.githubusercontent.com/62513924/209182984-b9ef39a4-8f68-42c3-b11f-2432840de159.jpg)

Apart from that, I don't know what is the end goals so can not provide you with any details.
Also, this is not an issue, I will recommend posting your queries in the Discussion section If the queries are not related to a code error. You can check the discussion section from the mentioned link below.
https://github.com/RizwanMunawar/yolov7-pose-estimation/discussions

**Comment by RizwanMunawar** [comment]
I am closing this issue for now. Feel free to open a new issue, If it's related to a code error. Otherwise, you can post your queries in the discussion section.
https://github.com/RizwanMunawar/yolov7-pose-estimation/discussions
