### ISSUE TITLE
No such file or directory: 'yolov7-w6-pose.pt'

### ISSUE THREAD

**Issue by jossevessies** [RizwanMunawar/yolov7-pose-estimation#16]
Dear Razwan,

Thank again. And this time... a true small error.
As I said, probably on my side, but I wouldn't know where to begin.
It seems to be an issue with loading the weights into torch.

Here the full log:

  File "C:\Users\josse\yolov7-pose-estimation\pose-estimate.py", line 202, in <module>
    strip_optimizer(opt.device,opt.poseweights)
  File "C:\Users\josse\yolov7-pose-estimation\utils\general.py", line 797, in strip_optimizer
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\josse\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\josse\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'yolov7-w6-pose.pt'

I hope you have a clue!

**Comment by RizwanMunawar** [comment]
@jossevessies! You will need to download the weights file "yolov7-w6-pose.pt" from mentioned link below.
https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-w6-pose.pt

BTW, it is clearly mentioned in the readme file. See step 7 in [Steps to run code](https://github.com/RizwanMunawar/yolov7-pose-estimation#steps-to-run-code)

**Comment by jossevessies** [comment]
Right. My bad.
Apologies.
I had installed everything a couple of months before and had it working.
This time I did the installation by heart.
Forgot there was this step.

Well, you remain great!

**Comment by RizwanMunawar** [comment]
@jossevessies! I am closing this issue. Feel free to open new issue, if you will face any errors.
