### ISSUE TITLE
how to train our own pose classification model?

### ISSUE THREAD

**Issue by akashAD98** [RizwanMunawar/yolov7-pose-estimation#2]
how to convert the coco format into our custom keypoint classification format?

**Comment by algomaks** [comment]
Is there a training script that we can use similar to the one in the https://github.com/RizwanMunawar/yolov7-segmentation repo?

**Comment by RizwanMunawar** [comment]
> Is there a training script that we can use similar to the one in the https://github.com/RizwanMunawar/yolov7-segmentation repo?

@algomaks! I am currently working on that, Soon it will be a part of the repository.

**Comment by RizwanMunawar** [comment]
@algomaks I am closing this issue, as it's related to enhancement not actually the issue, Thanks
