### ISSUE TITLE
hello.  I use web cam have some probleam. how can i adjust

### ISSUE THREAD

**Issue by chang556** [RizwanMunawar/yolov7-pose-estimation#3]
![image](https://user-images.githubusercontent.com/75434070/199195214-11e494db-ea87-4b70-bf27-a477de23d8d6.png)

**Comment by RizwanMunawar** [comment]
@chang556! I am working on webcam module, soon it will a part of main branch. If you want to contribute in webcam module, feel free to send pull request.

**Comment by Ishihara-Masabumi** [comment]
Me too.
I have the same problem.
I would appriciate it if you fix it push the correct module.

**Comment by Hooje** [comment]
I've fixed this issue, later I will send the pull request.

**Comment by RizwanMunawar** [comment]
@chang556 @Ishihara-Masabumi, @Hooje has resolved this issue, you can clone the latest code and can apply pose estimation using your webcams. 🤗

**Comment by Ishihara-Masabumi** [comment]
Thank you very much.

**Comment by chang556** [comment]
非常感謝
