### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolov7-w6-pose.pt'

### ISSUE THREAD

**Issue by Xeorox** [RizwanMunawar/yolov7-pose-estimation#5]
Where should the pose estimation model be put for it to work ?

**Comment by RizwanMunawar** [comment]
@Xeorox you can download the weights file from link mentioned below.
https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-w6-pose.pt

**Comment by RizwanMunawar** [comment]
I think the problem is solved, I am closing this issue. Feel free to open a new one, if you will face any problems.
