### ISSUE TITLE
Can't seem to find information on keypoint landmark order

### ISSUE THREAD

**Issue by sanjaythakur** [RizwanMunawar/yolov7-pose-estimation#7]
I want to use specific body landmark keypoints such as only the left and right shoulders from the predicted keypoints. However, I am unable to find consistent information anywhere on what is the order in which landmarks are arranged. They change depending on which website I refer to. Can anyone please point me to the right reliable resource for it?

Thanks.

**Comment by sanjaythakur** [comment]
Just to be clear, I understand there are 17 landmarks and each of them an (x,y,v)  ascribed to them. I just need reliable information on what is the order of the landmarks.

**Comment by RizwanMunawar** [comment]
@sanjaythakur! YOLOv7 pose estimation is based on 2d landmarks structure. You can get better idea about the order of landmarks from attached picture below.

![IMG-20221121-WA0005](https://user-images.githubusercontent.com/62513924/204121854-ba14ce4c-d9fd-4244-92b7-038ef93199af.jpg)

**Comment by RizwanMunawar** [comment]
@sanjaythakur! Your problem solved now?

**Comment by sanjaythakur** [comment]
@RizwanMunawar , yes got solved a few days ago. Thank you. @
