### ISSUE TITLE
Could you share your code for training?

### ISSUE THREAD

**Issue by wanghlsara** [RizwanMunawar/yolov7-pose-estimation#8]
The Pose-estimation result is amazing! Could you share your code for training? such as train.py, etc.

**Comment by RizwanMunawar** [comment]
@wanghlsara! Yes I am working on training module. Soon it will be a part of repository!

**Comment by RizwanMunawar** [comment]
@wanghlsara I am closing this issue for now, as it's not related to any error. It's a discussion about some addition To the code. Feel free to open a new issue if you will face any errors.
